"use client"
import React, { useEffect, useState, useRef } from 'react'
// import { io } from 'socket.io-client'
import { useSearchParams } from "next/navigation";
import { useRouter } from 'next/navigation';
import socket from '../../../socket';
import Peer from 'simple-peer';

function Page({ params }) {
    const router = useRouter();
    // const [socket, setSocket] = useState(null);
    const [currentUserId, setCurrentUserId] = useState(null);
    const [roomId, setRoomId] = useState(null);
    const [usersInRoom, setUsersInRoom] = useState([]);
    const [stream, setStream] = useState(null);
    const [peer, setPeer] = useState(null);

    // Use refs to store current values
    const userIdRef = useRef(null);
    const roomIdRef = useRef(null);
    const streamRef = useRef(null);
    const localVideoRef = useRef(null);
    const remoteVideoRef = useRef(null);
    const peerRef = useRef(null);

    // Update refs when states change
    useEffect(() => {
        userIdRef.current = currentUserId;
    }, [currentUserId]);

    useEffect(() => {
        roomIdRef.current = roomId;
    }, [roomId]);

    useEffect(() => {
        streamRef.current = stream;
    }, [stream]);

    useEffect(() => {
        const getMedia = async () => {
            try {
                const mediaStream = await navigator.mediaDevices.getUserMedia({
                    video: true,
                    audio: true
                });
                setStream(mediaStream);
                streamRef.current = mediaStream;

                if (localVideoRef.current) {
                    localVideoRef.current.srcObject = mediaStream;
                }
            } catch (err) {
                console.error("Error accessing media devices:", err);
            }
        };

        getMedia();

        return () => {
            if (streamRef.current) {
                streamRef.current.getTracks().forEach(track => track.stop());
            }
        };
    }, []);

    useEffect(() => {
        if (!stream) return;

        const initializeRoom = async () => {
            try {
                const response = await fetch("/api/getCurrentUser");
                const userData = await response.json();
                const currentRoomId = params.roomId;

                setCurrentUserId(userData.userId);
                setRoomId(currentRoomId);

                userIdRef.current = userData.userId;
                roomIdRef.current = currentRoomId;

                // Clean up previous listeners
                socket.off("userJoined");
                socket.off("userLeft");
                socket.off("usersInRoom");
                socket.off("signalData");

                // Set up signal data handler BEFORE joining room
                socket.on('signalData', (data) => {
                    console.log('Received signal from peer', data);
                    if (data.userId !== userData.userId && peerRef.current) {
                        console.log('Processing signal with current peer');
                        peerRef.current.signal(data.signal);
                    }
                });

                socket.on("usersInRoom", (users) => {
                    console.log("Users in room:", users);
                    setUsersInRoom(users);

                    // First user creates offer when second user joins
                    if (users.length === 2) {
                        if (users[0] === userData.userId) {
                            console.log("Creating offer as first user");
                            const newPeer = new Peer({
                                initiator: true,
                                stream: streamRef.current, // Use existing stream
                                trickle: false,
                                config: {
                                    iceServers: [
                                        { urls: 'stun:stun.l.google.com:19302' },
                                        { urls: 'stun:global.stun.twilio.com:3478' }
                                    ]
                                }
                            });

                            // Handle signals generated by this peer
                            newPeer.on('signal', (signal) => {
                                console.log('Generated signal as initiator', signal);
                                socket.emit('signal', {
                                    roomId: currentRoomId,
                                    userId: userData.userId,
                                    signal: signal
                                });
                            });

                            newPeer.on('stream', (remoteStream) => {
                                console.log("Received remote stream as initiator", remoteStream);
                                if (remoteVideoRef.current) {
                                    remoteVideoRef.current.srcObject = remoteStream;
                                }
                            });

                            // Update both state and ref
                            setPeer(newPeer);
                            peerRef.current = newPeer; // Update ref immediately
                        }
                        else {
                            console.log("Creating answer as second user");
                            const newPeer = new Peer({
                                initiator: false,
                                stream: streamRef.current, // Use existing stream
                                trickle: false,
                                config: {
                                    iceServers: [
                                        { urls: 'stun:stun.l.google.com:19302' },
                                        { urls: 'stun:global.stun.twilio.com:3478' }
                                    ]
                                }
                            });

                            // Handle signals generated by this peer
                            newPeer.on('signal', (signal) => {
                                console.log('Generated signal as responder', signal);
                                socket.emit('signal', {
                                    roomId: currentRoomId,
                                    userId: userData.userId,
                                    signal: signal
                                });
                            });

                            newPeer.on('stream', (remoteStream) => {
                                console.log("Received remote stream as responder", remoteStream);
                                if (remoteVideoRef.current) {
                                    remoteVideoRef.current.srcObject = remoteStream;
                                }
                            });

                            // Update both state and ref
                            setPeer(newPeer);
                            peerRef.current = newPeer; // Update ref immediately
                        }
                    }
                });

                socket.on("userLeft", (leftUserId) => {
                    console.log("User left:", leftUserId);
                    if (peer) {
                        peer.destroy();
                        setPeer(null);
                    }
                    if (remoteVideoRef.current) {
                        remoteVideoRef.current.srcObject = null;
                    }
                });


                // Join room
                socket.emit("joinRoom", currentRoomId, userData.userId);

            } catch (error) {
                console.error("Error initializing room:", error);
            }
        };

        initializeRoom();

        return () => {
            if (peerRef.current) {
                peerRef.current.destroy();
                peerRef.current = null;
            }
            if (peer) {
                setPeer(null);
            }
        };
    }, [stream]);

    const handleJoinAnotherRoom = async () => {
        if (peer) {
            peer.destroy();
            setPeer(null);
        }
        if (peerRef.current) {
            peerRef.current.destroy();
            peerRef.current = null;
        }
        if (stream) {
            stream.getTracks().forEach(track => track.stop());
        }
        socket.emit("leaveRoom", roomId, currentUserId);
        socket.emit("findRooms", currentUserId);
        socket.on("roomsFound", (rooms) => {
            console.log(rooms);
            router.push(`/videochat/${rooms[0]}`);
        });
        socket.on("noRoomsFound", () => {
            alert("No rooms found. Please create a new room.");
        });
        router.push("/videochat");
    }

    return (
        <div className='flex flex-col items-center justify-center h-screen'>
            <h1 className='text-2xl font-bold'>Video Chat Room</h1>
            <p className='text-lg'>Room ID: {roomId}</p>
            <p className='text-lg'>User ID: {currentUserId}</p>
            <div className='flex flex-col items-center justify-center'>
                <p className='text-lg'>Users in Room:</p>
                {usersInRoom.length > 0 ? usersInRoom.map((user) => (
                    <p key={user}>{user}</p>
                )) : <p>{currentUserId}</p>}
            </div>
            <div className='flex flex-row items-center justify-center gap-4 my-4'>
                <div className='relative'>
                    <video
                        ref={localVideoRef}
                        autoPlay
                        playsInline
                        muted
                        className='w-64 h-48 border-2 border-blue-500 rounded-lg'
                    />
                    <p className='absolute bottom-2 left-2 bg-black bg-opacity-50 px-2 py-1 text-white rounded'>You</p>
                </div>
                <div className='relative'>
                    <video
                        ref={remoteVideoRef}
                        autoPlay
                        playsInline
                        className='w-64 h-48 border-2 border-green-500 rounded-lg'
                    />
                    <p className='absolute bottom-2 left-2 bg-black bg-opacity-50 px-2 py-1 text-white rounded'>Peer</p>
                </div>
            </div>
            <div className='flex space-x-4 mt-4'>
                <button className='bg-red-500 text-white px-4 py-2 rounded-md hover:bg-red-600'
                    onClick={() => {
                        if (window.confirm("Are you sure you want to leave the room?")) {
                            if (peer) {
                                peer.destroy();
                                setPeer(null);
                            }
                            if (stream) {
                                stream.getTracks().forEach(track => track.stop());
                            }
                            socket.emit("leaveRoom", roomId, currentUserId);
                            router.push("/videochat");
                        }
                    }}>
                    Leave Room
                </button>
                <button className='bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600'
                    onClick={() => handleJoinAnotherRoom()}
                >Join Another Room</button>
            </div>
        </div>
    );
}

export default Page;
